### ISSUE TITLE
[bug] Stuck at "Waiting for Spy to connect to Reciever"

### ISSUE THREAD

**Issue by abumettleq** [MotionFlex0/XOPE-.NET#4]
![image](https://user-images.githubusercontent.com/84507882/205465957-dd3d6beb-3886-4562-880a-54f8b1c4d48e.png)

All files were compiled successfully. But somehow Spy is not connecting to reciever!

**Comment by abumettleq** [comment]
![image](https://user-images.githubusercontent.com/84507882/205466086-d5357471-f975-4851-8171-2d8bdc953dae.png)
Threads were made, but they weren't operating (0 cycles delta).

**Comment by MotionFlex0** [comment]
Currently, running XOPE as an admin requires the attached process to also be run as an admin or higher. A lower privileged process cannot currently communicate with XOPE. 

So, if the attached process is not running as an admin, don't run XOPE as an admin. I do plan on fixing this in the future.
