### ISSUE TITLE
Possible to block a packet like WPE Pro?

### ISSUE THREAD

**Issue by Thekidiacs** [MotionFlex0/XOPE-.NET#5]
Title says it all. @MotionFlex0 Is it possible?

**Comment by Thekidiacs** [comment]
Also, it works great this packet editor the only thing I think it might be missing is a block packet function.

**Comment by MotionFlex0** [comment]
I have added a drop packet option to the filter but I do have plans to add a better way to drop/edit/forward packets on the fly.
